fastlane_require "aws-sdk-ssm"
require_relative 'env'

default_platform(:ios)

before_all do
  Dotenv.overload "#{ENV["HOME"]}/.fastlane/.env.aws"

  unless ENV["AWS_ACCESS_KEY_ID"]
    UI.user_error! "AWS access not set up correctly. Expected to load a file in $HOME/.fastlane/.env.aws. Either create a file there or modify the path fastlane loads from."
  end
  Stack::Env.load_envs(['SENTRY_AUTH_TOKEN', 'SENTRY_DSN', 'ITUNES_CONNECT_TEAM_ID', 'APPLE_DEVELOPER_TEAM_ID', 'MATCH_PASSWORD', 'APPLE_ID', 'APPLE_ID_PASSWORD'])
end

platform :ios do

  lane :setup_env_file_for_app do
    dot_env_variables = [
      "APPENV",
      "APIURL",
      "SENTRY_DSN",
    ]
    Stack::Env.load_envs(dot_env_variables)

    contents = ""
    dot_env_variables.each do |key|
      if ENV[key] == nil
        UI.crash! "Missing environment value for #{key}"
      end
      contents += "#{key}=#{ENV[key]}\n"
    end

    #Can also do it this way if we want to
    contents = "APPENV=#{Stack::Env.APPENV}
APIURL=#{Stack::Env.APIURL}
SENTRY_DSN=#{Stack::Env.SENTRY_DSN}"

    #Write to a .env file which the app can use through react-native-config
    File.open("../.env", "w+") do |file|
      file.puts contents
    end
  end

end
